"""Syllabus PDF serving.

In MVP we look for a file at  data/pdfs/syllabus_sem{N}.pdf
and stream it back. If no PDF exists for the semester, we
generate a small placeholder PDF on the fly so the UI never 404s.
"""
from io import BytesIO
from pathlib import Path
from datetime import datetime

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response, FileResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

from app.core.config import settings

router = APIRouter()

# A short list of placeholder subjects for the on-the-fly PDF
PLACEHOLDER_SYLLABUS = {
    1: [
        ("BSC101", "Engineering Mathematics-I"),
        ("BSC102", "Engineering Physics"),
        ("ESC101", "Problem Solving with C"),
        ("ESC102", "Basic Electrical Engineering"),
        ("HSMC101", "English"),
    ],
    2: [
        ("BSC201", "Engineering Mathematics-II"),
        ("BSC202", "Engineering Chemistry"),
        ("ESC201", "Python Programming"),
        ("ESC202", "Basic Electronics"),
        ("ESC203", "Engineering Mechanics"),
    ],
    3: [
        ("BCS301", "Data Structures"),
        ("BCS302", "Discrete Mathematical Structures"),
        ("BCS303", "Digital Design & Computer Organization"),
        ("BCS304", "Object Oriented Programming with Java"),
    ],
    4: [
        ("BCS401", "Operating Systems"),
        ("BCS402", "Design & Analysis of Algorithms"),
        ("BCS403", "Database Management Systems"),
        ("BCS404", "Microcontrollers"),
    ],
    5: [
        ("BCS501", "Computer Networks"),
        ("BCS502", "Theory of Computation"),
        ("BCS503", "Software Engineering"),
        ("BCS504", "Machine Learning"),
    ],
    6: [
        ("BCS601", "Cloud Computing"),
        ("BCS602", "Compiler Design"),
        ("BCS603", "Information Security"),
        ("BCS604", "Web Technologies"),
    ],
    7: [
        ("BCS701", "Artificial Intelligence"),
        ("BCS702", "Distributed Systems"),
        ("BCS703", "Deep Learning"),
        ("BCS704", "Project Work Phase-I"),
    ],
    8: [
        ("BCS801", "Internet of Things"),
        ("BCS802", "Blockchain Technology"),
        ("BCS803", "Project Work Phase-II"),
        ("BCS804", "Internship"),
    ],
}


def _build_placeholder_pdf(semester: int) -> bytes:
    """Generate a small placeholder syllabus PDF for the given semester."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title=f"UVCE Syllabus - Semester {semester}",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"], fontSize=24,
        textColor=colors.HexColor("#0a0a0b"),
        spaceAfter=20,
    )
    h2 = ParagraphStyle(
        "H2", parent=styles["Heading2"], textColor=colors.HexColor("#f5b800"),
        spaceBefore=12, spaceAfter=8,
    )
    body = styles["BodyText"]

    story = []
    story.append(Paragraph(f"UVCE — Semester {semester} Syllabus", title_style))
    story.append(Paragraph(
        f"Auto-generated placeholder syllabus · {datetime.now().strftime('%B %Y')}",
        body
    ))
    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph(
        "This is a placeholder PDF generated by the UVCE ExamMate AI backend. "
        "Replace it by uploading the real syllabus via the Community Knowledge "
        "Base section, or by placing a file at "
        "<font face='Courier'>backend/data/pdfs/syllabus_sem{}.pdf</font>.".format(semester),
        body
    ))
    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph("Subjects in this semester", h2))

    for code, name in PLACEHOLDER_SYLLABUS.get(semester, []):
        story.append(Paragraph(f"• <b>{code}</b> — {name}", body))

    doc.build(story)
    return buf.getvalue()


@router.get("/syllabus/{semester}/pdf")
def get_syllabus(semester: int):
    if semester < 1 or semester > 8:
        raise HTTPException(404, "Invalid semester (must be 1-8)")

    candidate = Path(settings.data_dir) / f"syllabus_sem{semester}.pdf"
    if candidate.exists():
        return FileResponse(
            candidate,
            media_type="application/pdf",
            filename=f"syllabus_sem{semester}.pdf",
        )

    # No real file? Generate placeholder on the fly so the UI never 404s.
    pdf_bytes = _build_placeholder_pdf(semester)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'inline; filename="syllabus_sem{semester}.pdf"',
        },
    )
